// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Program;

namespace SPSqlProvider.Migrations
{
    [DbContext(typeof(NorthwindContext))]
    partial class NorthwindContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bug29556121.TestModels.MostExpensiveProduct", b =>
                {
                    b.Property<string>("TenMostExpensiveProducts")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ＴenMostExpensiveProducts");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnName("ＵnitPrice");

                    b.HasKey("TenMostExpensiveProducts");

                    b.ToTable("ＭostExpensiveProducts");
                });

            modelBuilder.Entity("bug29556121.TestModels.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ＰroductID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Discontinued")
                        .HasColumnName("Ｄiscontinued");

                    b.Property<string>("ProductName")
                        .HasColumnName("ＰroductName");

                    b.Property<int?>("SupplierID")
                        .HasColumnName("ＳupplierID");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnName("ＵnitPrice");

                    b.Property<int>("UnitsInStock")
                        .HasColumnName("ＵnitsInStock");

                    b.HasKey("ProductID");

                    b.ToTable("Ｐroducts");
                });
#pragma warning restore 612, 618
        }
    }
}
